name: Mirror to Codeberg

on:
  pull_request:
    types: [closed]
  push:
    tags: ['v*']
  delete:
    branches: ['**']
    tags: ['v*']
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    # mirror on:
    # - branch delete
    # - tag push
    # - tag delete
    # - fork PR merge
    if: |
      github.event_name != 'pull_request' ||
      (
        github.event.pull_request.merged == true &&
        github.event.pull_request.head.repo.full_name != github.repository
      )
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror to Codeberg
        run: |
          git remote add codeberg \
            https://$CODEBERG_USER:$CODEBERG_TOKEN@codeberg.org/$CODEBERG_USER/$(basename $GITHUB_REPOSITORY).git
          git push --mirror codeberg
        env:
          CODEBERG_USER: 'nggit'
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
